appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: hf74Mw0/B3X1DasN42VTb54ZhLUpfrW6oSyhonf33S4P5bN0Y14SkafeBdA2qNMQ1BPPvtKNu27LYNFWXCcvZ2ENZf0H3Vrj6mBjMm/RF4XKKwKCJE8HaUvjWO5S5VKwIcLn11/9o1ATB7JUUUHhiOd5Dtl7NikkOWFYzU2YTLhUUg5bxdJWTYZu+e8rL4aKVjRJE7gjLSEAOppEwIFbPKT740p9ItmY8PtBq1tCMoUzj8K/wzqRqstqGUgnaK0FAo0Zx6teT2MAzw0BZuyATEry7tkyqru6fveB5b/9Dy04bsQIWE/d0Rdeigsy0zi2ido81cAfr6AQiNk2kDgKMZNP3pii7xKRzEtCsrIgiSCX8XqGohnT/pn4Xfi+6rlHNt4o4KiNpHM7xTJGEtAmEc2cFg4LroZoFCC9KejU8Y/OMy49/bMUl7nLEjGwTRK/ov8cggNbDaIM/IS7Y52vZcyMFgsoAOuoCsSNNqFwj9D4r6hGK8HGHdHo+zYS2X9I5JrZUp5In8pInG1J16c/Be8n7/g2QeykyHRuWU4+TezsFtRyNYsiHtU6zNCjCmSBcrvbd8gLK3ofUAFkdd7/9napljrAVtrpV3xmI/0w/S/JXP+2ZwR31MeR4gB9UHQexrjC7cwJxupnLEjcUtG3r5LdUHJhTnKWcQOzp1vLrSc=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
